version: 0.0
os: linux
files:
    - source: /
      destination: /home/ubuntu/bluexinga-backend
hooks:
  BeforeInstall:
    - location: scripts/before_script.sh
      runas: root
  
  AfterInstall:
    - location: scripts/after_script.sh
      runas: root